use_frameworks!

target 'SwiftyFitsize_OC' do
    pod 'SwiftyFitsize', :path => '../'
end

target 'SwiftyFitsize_Swift' do
  pod 'SwiftyFitsize', :path => '../'
  
  pod 'LXFProtocolTool/LXFNibloadable'

  target 'SwiftyFitsize_SwiftTests' do
    inherit! :search_paths

    
  end
end
