use_frameworks!

project 'SwiftyFitsize.xcodeproj'

target 'SwiftyFitsize_OC' do
    pod 'SwiftyFitsize', :path => '../'
end

target 'SwiftyFitsize_Swift' do
  pod 'SwiftyFitsize', :path => '../'
  
  pod 'SnapKit'

  target 'SwiftyFitsize_SwiftTests' do
    inherit! :search_paths

    
  end
end

target 'SwiftyFitsize_Scene' do
    pod 'SwiftyFitsize', :path => '../'
    pod 'SnapKit'
end
